//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.SchoolManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecordAgreementSigned_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordAgreementSigned_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.SchoolManagement.RecordAgreementSigned.Messages", typeof(RecordAgreementSigned_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj datę zakończenia umowy.
        /// </summary>
        public static string AgreementEndDate_cannot_be_empty {
            get {
                return ResourceManager.GetString("AgreementEndDate cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia umowy musi wypadać w przyszłości.
        /// </summary>
        public static string AgreementEndDate_must_be_in_the_future {
            get {
                return ResourceManager.GetString("AgreementEndDate must be in the future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj czas trwania umowy.
        /// </summary>
        public static string Duration_cannot_be_empty {
            get {
                return ResourceManager.GetString("Duration cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umowa na czas nieokreślony nie może mieć daty zakończenia.
        /// </summary>
        public static string PermanentAgreement_cannot_have_AgreementEndDate {
            get {
                return ResourceManager.GetString("PermanentAgreement cannot have AgreementEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skan umowy musi zajmować mniej niż 10MB.
        /// </summary>
        public static string ScannedDocument_cannot_be_bigger_than_10MB {
            get {
                return ResourceManager.GetString("ScannedDocument cannot be bigger than 10MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prześlij skan umowy.
        /// </summary>
        public static string ScannedDocument_cannot_be_empty {
            get {
                return ResourceManager.GetString("ScannedDocument cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScannedDocumentContentType cannot be empty.
        /// </summary>
        public static string ScannedDocumentContentType_cannot_be_empty {
            get {
                return ResourceManager.GetString("ScannedDocumentContentType cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScannedDocumentExtension cannot be empty.
        /// </summary>
        public static string ScannedDocumentExtension_cannot_be_empty {
            get {
                return ResourceManager.GetString("ScannedDocumentExtension cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScannedDocumentExtension must start with a dot (.).
        /// </summary>
        public static string ScannedDocumentExtension_must_start_with_a_dot {
            get {
                return ResourceManager.GetString("ScannedDocumentExtension must start with a dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolId cannot be empty.
        /// </summary>
        public static string SchoolId_cannot_be_empty {
            get {
                return ResourceManager.GetString("SchoolId_cannot_be_empty", resourceCulture);
            }
        }
    }
}
