//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.SchoolManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecordContact_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordContact_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.SchoolManagement.RecordContact.Messages", typeof(RecordContact_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak doszło do kontaktu?.
        /// </summary>
        public static string CommunicationChannel_cannot_be_empty {
            get {
                return ResourceManager.GetString("CommunicationChannel cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data i czas kontaktu muszą być wcześniejsze niż bieżący czas.
        /// </summary>
        public static string Contact_timestamp_cannot_be_later_than_current_timestamp {
            get {
                return ResourceManager.GetString("Contact timestamp cannot be later than current timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj imię i nazwisko osoby z którą doszło do kontaktu.
        /// </summary>
        public static string ContactPersonName_cannot_be_empty {
            get {
                return ResourceManager.GetString("ContactPersonName_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opisz treść kontaktu.
        /// </summary>
        public static string Content_cannot_be_empty {
            get {
                return ResourceManager.GetString("Content cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj adres e-mail kontaktu.
        /// </summary>
        public static string EmailAddress_cannot_be_empty_when_CommunicationChannel_is_IncomingEmail_or_OutgoingEmail {
            get {
                return ResourceManager.GetString("EmailAddress_cannot_be_empty_when_CommunicationChannel_is_IncomingEmail_or_Outgoi" +
                        "ngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj numer telefonu kontaktu.
        /// </summary>
        public static string PhoneNumber_cannot_be_empty_when_CommunicationChannelType_is_IncomingPhone_or_OutgoingPhone {
            get {
                return ResourceManager.GetString("PhoneNumber_cannot be empty when CommunicationChannelType is IncomingPhone or Out" +
                        "goingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj identyfikator szkoły.
        /// </summary>
        public static string SchoolId_cannot_be_empty {
            get {
                return ResourceManager.GetString("SchoolId_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj datę i czas kontaktu.
        /// </summary>
        public static string Timestamp_cannot_be_empty {
            get {
                return ResourceManager.GetString("Timestamp_cannot_be_empty", resourceCulture);
            }
        }
    }
}
