//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.SchoolManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterSchool_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterSchool_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.SchoolManagement.RegisterSchool.Messages", typeof(RegisterSchool_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj adres szkoły.
        /// </summary>
        public static string Address_Cannot_be_empty {
            get {
                return ResourceManager.GetString("Address_Cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj miasto.
        /// </summary>
        public static string City_CannotBeEmpty {
            get {
                return ResourceManager.GetString("City_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj co najmniej jeden kontakt do szkoły.
        /// </summary>
        public static string ContactData_cannot_be_empty {
            get {
                return ResourceManager.GetString("ContactData cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresy e-mail i numery telefonu nie mogą się powtarzać.
        /// </summary>
        public static string ContactData_emails_and_phone_numbers_cannot_repeat_themselves {
            get {
                return ResourceManager.GetString("ContactData_emails and phone numbers cannot repeat themselves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj co najmniej jeden kontakt do szkoły (adres e-mail lub numer telefonu).
        /// </summary>
        public static string Either_ContactData_PhoneNumber_or_ContactData_EmailAddress_must_be_provided {
            get {
                return ResourceManager.GetString("Either ContactData.PhoneNumber or ContactData.EmailAddress must be provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę szkoły.
        /// </summary>
        public static string SchoolName_CannotBeEmpty {
            get {
                return ResourceManager.GetString("SchoolName_CannotBeEmpty", resourceCulture);
            }
        }
    }
}
