//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.Recruitment.Trainings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.Recruitment.Trainings.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można dodać zaplanowanego szkolenia po rozpoczęciu kampanii.
        /// </summary>
        public static string CannotScheduleTrainingAfterCampaignStart {
            get {
                return ResourceManager.GetString("CannotScheduleTrainingAfterCampaignStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplanowane szkolenie musi się odbyć w trakcie edycji, do której przypisana jest kampania.
        /// </summary>
        public static string CannotScheduleTrainingAfterEditionEnd {
            get {
                return ResourceManager.GetString("CannotScheduleTrainingAfterEditionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zaplanowaniego szkolenia już minęła.
        /// </summary>
        public static string CannotScheduleTrainingInThePast {
            get {
                return ResourceManager.GetString("CannotScheduleTrainingInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatka musi zawierać treść.
        /// </summary>
        public static string NoteCannotBeEmpty {
            get {
                return ResourceManager.GetString("NoteCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplanowane szkolenie nie może się odbyć przed zakończeniem kampanii rekrutacyjnej.
        /// </summary>
        public static string ScheduledTrainingMustOccurAfterCampaignEnd {
            get {
                return ResourceManager.GetString("ScheduledTrainingMustOccurAfterCampaignEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data i godzina rozpoczęcia szkolenia nie może być późniejsza niż data i godzina zakończenia.
        /// </summary>
        public static string StartDateTimeCannotBeGreaterThanEndDateTime {
            get {
                return ResourceManager.GetString("StartDateTimeCannotBeGreaterThanEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkolenie musi rozpocząć się i zakończyć tego samego dnia.
        /// </summary>
        public static string Training_must_begin_and_end_on_the_same_day {
            get {
                return ResourceManager.GetString("Training must begin and end on the same day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono szkolenia.
        /// </summary>
        public static string TrainingNotFound {
            get {
                return ResourceManager.GetString("TrainingNotFound", resourceCulture);
            }
        }
    }
}
