//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.Recruitment.Enrollments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecordAcceptedTrainingInvitation_ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordAcceptedTrainingInvitation_ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.Recruitment.Enrollments.RecordAcceptedTrainingInvitation.ErrorMessages", typeof(RecordAcceptedTrainingInvitation_ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate has already completed his training.
        /// </summary>
        public static string CandidateAlreadyCompletedTheTraining {
            get {
                return ResourceManager.GetString("CandidateAlreadyCompletedTheTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected training was not found.
        /// </summary>
        public static string TrainingNotFound {
            get {
                return ResourceManager.GetString("TrainingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected training time already passed.
        /// </summary>
        public static string TrainingTimeAlreadyPassed {
            get {
                return ResourceManager.GetString("TrainingTimeAlreadyPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected training was not specified among preferred trainings.
        /// </summary>
        public static string TrainingWasNotSpecifiedAsPreferred {
            get {
                return ResourceManager.GetString("TrainingWasNotSpecifiedAsPreferred", resourceCulture);
            }
        }
    }
}
