//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.Recruitment.Enrollments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SendTrainingReminder_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SendTrainingReminder_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.Recruitment.Enrollments.SendTrainingReminder.Messages", typeof(SendTrainingReminder_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie musi być wysłane przed rozpoczęciem szkolenia..
        /// </summary>
        public static string Reminder_cannot_be_sent_after_training_start {
            get {
                return ResourceManager.GetString("Reminder cannot be sent after training start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie może zostać wysłane maksymalnie 24 godziny przed rozpoczęciem szkolenia..
        /// </summary>
        public static string Reminder_cannot_be_sent_earlier_than_24h_before_training {
            get {
                return ResourceManager.GetString("Reminder cannot be sent earlier than 24h before training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandydat nie jest zaproszony na szkolenie, nie można wysłać przypomnienia..
        /// </summary>
        public static string Reminder_cannot_be_sent_if_the_candidate_is_not_invited_to_training {
            get {
                return ResourceManager.GetString("Reminder cannot be sent if the candidate is not invited to training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandydat zrezygnował, nie można wysłać przypomnienia..
        /// </summary>
        public static string Reminder_cannot_be_sent_if_the_candidate_resigned {
            get {
                return ResourceManager.GetString("Reminder cannot be sent if the candidate resigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono szkolenia..
        /// </summary>
        public static string Training_not_found {
            get {
                return ResourceManager.GetString("Training not found", resourceCulture);
            }
        }
    }
}
