//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szlem.Recruitment.Enrollments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitRecruitmentForm_ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitRecruitmentForm_ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szlem.Recruitment.Enrollments.SubmitRecruitmentForm.ErrorMessages", typeof(SubmitRecruitmentForm_ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcja &quot;O mnie&quot; jest wymagana.
        /// </summary>
        public static string AboutMeIsRequired {
            get {
                return ResourceManager.GetString("AboutMeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy określić kampanię rekrutacyjną.
        /// </summary>
        public static string CampaignMustBeSpecified {
            get {
                return ResourceManager.GetString("CampaignMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczono powtarzające się szkolenia. Usuń duplikaty..
        /// </summary>
        public static string DuplicatePreferredTrainingsWereSpecified {
            get {
                return ResourceManager.GetString("DuplicatePreferredTrainingsWereSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail jest wymagany.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię jest wymagane.
        /// </summary>
        public static string FirstNameIsRequired {
            get {
                return ResourceManager.GetString("FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli chcesz uczestniczyć w rekrutacji, musisz wyrazić zgodę na przetwarzanie swoich danych osobowych..
        /// </summary>
        public static string GdprConsentIsRequired {
            get {
                return ResourceManager.GetString("GdprConsentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To nie jest poprawny adres e-mail.
        /// </summary>
        public static string Invalid_email_address {
            get {
                return ResourceManager.GetString("Invalid email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko jest wymagane.
        /// </summary>
        public static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu jest wymagany.
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowane miasta prowadzenia zajęć nie mogą się powtarzać.
        /// </summary>
        public static string PreferredLecturingCities_cannot_have_duplicates {
            get {
                return ResourceManager.GetString("PreferredLecturingCities cannot have duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaznaczyć co najmniej jedno preferowane miasto prowadzenia zajęć.
        /// </summary>
        public static string PreferredLecturingCities_must_be_specified {
            get {
                return ResourceManager.GetString("PreferredLecturingCities must be specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowane szkolenia muszą należeć do tej samej kampanii rekrutacyjnej.
        /// </summary>
        public static string PreferredTrainingsMustBelongToTheSameCampaign {
            get {
                return ResourceManager.GetString("PreferredTrainingsMustBelongToTheSameCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz zaznaczyć co najmniej jedno preferowane szkolenie.
        /// </summary>
        public static string PreferredTrainingsMustBeSpecified {
            get {
                return ResourceManager.GetString("PreferredTrainingsMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedno lub więcej z preferowanych szkoleń już się odbyło.
        /// </summary>
        public static string PreferredTrainingsMustOccurInTheFuture {
            get {
                return ResourceManager.GetString("PreferredTrainingsMustOccurInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred trainings with IDs {0} not found.
        /// </summary>
        public static string PreferredTrainingsNotFound {
            get {
                return ResourceManager.GetString("PreferredTrainingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/województwo są wymagane.
        /// </summary>
        public static string RegionIsRequired {
            get {
                return ResourceManager.GetString("RegionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektóre szkolenia nie zostały znalezione.
        /// </summary>
        public static string SomeTrainingsWereNotFound {
            get {
                return ResourceManager.GetString("SomeTrainingsWereNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swoja kandydaturę możesz zgłosić tylko w trakcie kampanii rekrutacyjnej.
        /// </summary>
        public static string SubmissionMustOccurDuringCampaign {
            get {
                return ResourceManager.GetString("SubmissionMustOccurDuringCampaign", resourceCulture);
            }
        }
    }
}
